#!/usr/bin/env -S nix shell nixpkgs#qmk --command bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)

cd "$(dirname "$0")"
qmk compile

mkdir -p mnt_flash
sudo mount /dev/disk/by-label/RPI-RP2 ./mnt_flash
sudo cp "${PROJECT_ROOT}"/splitkb_aurora_sofle_v2_rev1_xabufr.uf2 ./mnt_flash/
sudo umount ./mnt_flash
